import type { Metadata } from "next";
import { Inter, Nunito, Lato } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "@/app/globals.css";
import { hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { ReactQueryProvider } from "@/features/providers/react-query-provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { LocaleDropdownProvider } from "@/features/locale-dropdown/locale-dropdown-provider";
import { LocationManagerProvider } from "@/features/location-manager/location-manager-provider";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${nunito.className} ${lato.className} ${inter.className} antialiased min-w-[380px]`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <LocaleDropdownProvider>
            <ReactQueryProvider>
              <LocationManagerProvider>{children}</LocationManagerProvider>
            </ReactQueryProvider>
          </LocaleDropdownProvider>
        </NextIntlClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
